### ISSUE TITLE
Error Debug info after quick cleaning few files that was recomended

### ISSUE THREAD

**Issue by kubistonek** [loot/falloutnv#99]
In game npc appear without weapon, sometimes run straignt for no reason, and cant interact with them
error, Debug info:

[05:24:41.678611] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[05:24:44.191981] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[05:25:27.885347] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The server name or address could not be resolved
: libgit2 error
[05:25:27.919492] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5723: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5723:9239)
[05:25:29.001299] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FunctionalPostGameEnding-AWOPPatch.esp"]
[05:25:29.002360] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-YUP.esp"]
[05:25:29.002445] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-PN-Equipment.esp"]
[05:25:29.002708] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-UncutWastelandNPCs.esp"]
[05:25:29.003863] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="ProjectNevada-IMPACT.esp"]
[05:25:29.003945] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="TheModConfigurationMenu.esp"]
[05:25:29.004197] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FPSCounter.esp"]
[05:25:29.004324] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FalloutNV_lang.esp"]
[05:25:29.004546] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="RSO-RealisticStealthOverhaul-NV.esp"]
[05:25:29.004669] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="PN-RebalanceSneakOverrideremoval.esp"]
[05:25:29.004868] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="CASMwithMCM.esp"]
[05:25:29.005016] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="CompleteRespec.esp"]
[05:25:29.005229] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FNVRealisticWastelandLighting-AllDLC.esp"]
[05:25:29.005373] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="LilFixes.esp"]
[05:25:29.005531] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-DeadMoney.esp"]
[05:25:29.005673] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-FalloutNewVegas-TS.esp"]
[05:25:29.005872] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-HonestHearts.esp"]
[05:25:29.006036] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-LonesomeRoad.esp"]
[05:25:29.006264] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="DelayDLC-DM+HH+OWB+LR+GRA.esp"]
[05:25:29.006492] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FunctionalPostGameEnding-YUPPatch.esp"]
[05:25:29.006719] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="PlatinumRadio.esp"]
[05:25:29.006955] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="Conelrad640-1240.esp"]
[05:25:29.007414] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="InteriorLightingOverhaul-UltimateEdition.esp"]
[05:25:29.007738] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="ILO-GSShack.esp"]
[05:26:34.490901] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-JSU.esp"]
[05:26:34.491012] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-YUP.esp"]
[05:26:34.491065] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-PN-Equipment.esp"]
[05:26:34.491131] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-UncutWastelandNPCs.esp"]
[05:26:34.491479] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="LilFixes.esp"]
[05:26:34.491547] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-DeadMoney.esp"]
[05:26:34.491612] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-FalloutNewVegas-TS.esp"]
[05:26:34.491725] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-HonestHearts.esp"]
[05:26:34.491836] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-LonesomeRoad.esp"]
[05:26:34.491948] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="ProjectNevada-IMPACT.esp"]
[05:26:34.492106] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="TheModConfigurationMenu.esp"]
[05:26:34.492164] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FPSCounter.esp"]
[05:26:34.492234] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FalloutNV_lang.esp"]
[05:26:34.492361] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="RSO-RealisticStealthOverhaul-NV.esp"]
[05:26:34.492473] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="PN-RebalanceSneakOverrideremoval.esp"]
[05:26:34.492584] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="CASMwithMCM.esp"]
[05:26:34.492693] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="CompleteRespec.esp"]
[05:26:34.492799] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="DelayDLC-DM+HH+OWB+LR+GRA.esp"]
[05:26:34.492908] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FunctionalPostGameEnding-YUPPatch.esp"]
[05:26:34.493015] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="PlatinumRadio.esp"]
[05:26:34.493127] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="Conelrad640-1240.esp"]
[05:26:34.493230] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="InteriorLightingOverhaul-UltimateEdition.esp"]
[05:26:34.493341] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="ILO-GSShack.esp"]
[05:26:34.493450] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FNVRealisticWastelandLighting-AllDLC.esp"]
[05:26:35.605357] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The server name or address could not be resolved
: libgit2 error
[05:26:35.608978] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5723: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5723:9239)
[05:26:36.478466] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FunctionalPostGameEnding-AWOPPatch.esp"]
[05:26:36.479113] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-YUP.esp"]
[05:26:36.479395] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-PN-Equipment.esp"]
[05:26:36.479789] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="BraveNewWorld-UncutWastelandNPCs.esp"]
[05:26:36.480709] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="ProjectNevada-IMPACT.esp"]
[05:26:36.480915] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="TheModConfigurationMenu.esp"]
[05:26:36.481140] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FPSCounter.esp"]
[05:26:36.481390] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FalloutNV_lang.esp"]
[05:26:36.481588] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="RSO-RealisticStealthOverhaul-NV.esp"]
[05:26:36.481780] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="PN-RebalanceSneakOverrideremoval.esp"]
[05:26:36.482001] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="CASMwithMCM.esp"]
[05:26:36.482213] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="CompleteRespec.esp"]
[05:26:36.482402] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FNVRealisticWastelandLighting-AllDLC.esp"]
[05:26:36.482527] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="LilFixes.esp"]
[05:26:36.482674] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-DeadMoney.esp"]
[05:26:36.482968] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-FalloutNewVegas-TS.esp"]
[05:26:36.483044] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-HonestHearts.esp"]
[05:26:36.483245] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="NightsareDarker-LonesomeRoad.esp"]
[05:26:36.483378] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="DelayDLC-DM+HH+OWB+LR+GRA.esp"]
[05:26:36.483558] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="FunctionalPostGameEnding-YUPPatch.esp"]
[05:26:36.483825] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="PlatinumRadio.esp"]
[05:26:36.484093] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="Conelrad640-1240.esp"]
[05:26:36.484372] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="InteriorLightingOverhaul-UltimateEdition.esp"]
[05:26:36.484598] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4940: Uncaught Error: Expected element to have a child matching the selector [data-id="ILO-GSShack.esp"]

**Comment by pStyl3** [comment]
`In game npc appear without weapon, sometimes run straignt for no reason, and cant interact with them`
While unfortunate, this is not information that can help fix issues with the LOOT application. If you can tell us that plugin a must load after plugin b, for example, that's one thing that could be implemented.

These lines from the DebugLog
`Uncaught Error: Expected element to have a child matching the selector [data-id="FunctionalPostGameEnding-AWOPPatch.esp"]`

are more interesting. Please go to LOOT's settings, enable (full) debug logging, and provide us with the resulting `LOOTDebugLog.txt`.

**Comment by Ortham** [comment]
@kubistonek  It should be included in the debug log mentioned by @pStyl3, but it would also help to let us know the version of LOOT you're running.
